const express = require("express");
const {
  findAllItems,
  addItem,
} = require("../controllers/orderItemsController");
const router = express.Router();

// EN ESTA PARTE DEL CHECKOUT PODEMOS APRECIAR LO QUE SERÍAN LAS RUTAS DE LOS ITEMS

// ESTA RUTA GET LO QUE HACE ES RECIBIR EL ID DEL TICKET POR PARAMETRO, EN BASE A ESO ENCUENTRA TODOS LOS ITEMS QUE PERTENEZCAN
// A ESE TICKET, Y EN ESTE PEDIDO TE INCLUYE LO QUE SERÍAN LOS DATOS DEL PRODUCTO Y EL TICKET AL QUE PERTENECE
router.get("/:id", findAllItems);

// EN ESTE PEDIDO POST RECIBE DESDE EL FRONT EL ID DEL PRODUCTO, EL ID DEL TICKET Y LA CANTIDAD DE UNIDADES DE ESE PRODUCTO
// EN CASO DE QUE EL ID DEL TICKET ESTE MAL VA A DEVOLER UN BAD REQUEST 400, SINO ES EL CASO, VA A CREAR LA FILA EN LA BASE
// DE DATOS CON LOS DATOS QUE NOS LLEGO DESDE EL FRONT
router.post("/add", addItem);

module.exports = router;
